version: '2'
services:
  nginx:
    image: "nginx"
    depends_on:
      - web
    ports:
      - "${EXTERNAL_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  web:
    build:
      context: webapp
    volumes:
      - ./webapp:/app
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
